#! /bin/sh

# Autostart applications
$HOME/.config/bspwm/autostart.sh

# update x resources db 
xrdb -merge $HOME/.Xresources & 

# set the cursor 
xsetroot -cursor_name left_ptr &

# set the wallpaper
$HOME/.fehbg &

# launch Polybar
$HOME/.config/polybar/launch.sh &

# Get colors
BACKGROUND=$($HOME/.scripts/find-colors.sh background)
echo $BACKGROUND > /dev/tty2

bspc monitor -d TTY WEB SOC SYS FUN

bspc config border_width         8
bspc config window_gap          12
bspc config normal_border_color  "$BACKGROUND"
bspc config focused_border_color "$BACKGROUND"

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Firefox desktop='^2' follow=on
bspc rule -a URxvt:urxvt-floating state=floating follow=on focus=on
# for anyone confused, there is a script called "urxvt-floating" in /usr/bin/ which just calls urxvt
