#! /bin/sh

# Start sxhkd
sxhkd -c $HOME/.config/sxhkd/sxhkdrc &

# Autostart applications
$HOME/.config/bspwm/autostart.sh

# Get colors
BACKGROUND=$(/home/katkak/.scripts/find-colors.sh background)

bspc monitor -d TTY WEB SOC SYS FUN

bspc config border_width         8
bspc config window_gap          12
bspc config normal_border_color  $BACKGROUND
bspc config focused_border_color $BACKGROUND 

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Gimp desktop='^5' state=floating follow=on
bspc rule -a Firefox desktop='^2' follow=on
